apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_DATABASE_PASSWORD: UEFTU1dPUkQ= # "PASSWORD" base64 encoded
  MYSQL_DATABASE_NAME: QnVja2V0TGlzdA==  # "BucketList" base64 encoded